[CmdletBinding()]
param(
    [switch]$Print
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")
$memoryDir = Join-Path $repoRoot "docs\agent-memory"
$outputPath = Join-Path $memoryDir "compiled-memory.md"

$orderedPaths = @(
    "docs/agent-memory/current-state.md",
    "docs/agent-memory/progress.md",
    "docs/agent-memory/issues.md",
    "docs/agent-memory/decisions.md",
    "docs/agent-memory/session-log.md",
    "docs/agent-memory/revert-log.md",
    "docs/agent-memory/README.md",
    "README.md",
    "PROJECT_CHARTER.md",
    "docs/architecture/project-map.md",
    "docs/architecture/research-lifecycle.md",
    "docs/architecture/reproducibility-contract.md",
    "docs/architecture/source-package-manifest.md",
    "docs/research/research-plan.md",
    "experiments/registry.md"
)

if (-not (Test-Path -LiteralPath $memoryDir)) {
    throw "Memory directory not found: $memoryDir"
}

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"

$gitStatusText = "Unknown"
try {
    $gitOutput = & git -C $repoRoot status --short 2>&1
    if ($LASTEXITCODE -eq 0) {
        if ($gitOutput) {
            $gitStatusText = ($gitOutput -join [Environment]::NewLine)
        }
        else {
            $gitStatusText = "Clean"
        }
    }
    else {
        $gitStatusText = "Not a Git repository or git status failed: $($gitOutput -join ' ')"
    }
}
catch {
    $gitStatusText = "Git check failed: $($_.Exception.Message)"
}

$sections = [System.Collections.Generic.List[string]]::new()
$sections.Add("# Compiled Agent Memory")
$sections.Add("")
$sections.Add("Generated: $timestamp")
$sections.Add("")
$sections.Add('This file is generated by `scripts/agent-memory-start.ps1`. Do not edit it directly.')
$sections.Add("")
$sections.Add("## Git Status")
$sections.Add("")
$sections.Add('```text')
$sections.Add($gitStatusText)
$sections.Add('```')
$sections.Add("")

foreach ($relativePath in $orderedPaths) {
    $path = Join-Path $repoRoot $relativePath
    $displayPath = $relativePath -replace "\\", "/"
    $sections.Add("## Source: $displayPath")
    $sections.Add("")

    if (Test-Path -LiteralPath $path) {
        $content = Get-Content -Raw -LiteralPath $path
        $sections.Add($content.TrimEnd())
    }
    else {
        $sections.Add("Missing file: $displayPath")
    }

    $sections.Add("")
}

$compiled = $sections -join [Environment]::NewLine
Set-Content -LiteralPath $outputPath -Value $compiled -Encoding UTF8

Write-Host "Agent memory pulled into: $outputPath"

if ($Print) {
    Write-Output $compiled
}
